### ISSUE TITLE
支持相机扫描身份证信息吗

### ISSUE THREAD

**Issue by zdkcxy** [HonestMan123/ALiOCRDemo#1]
支持相机扫描身份证信息吗

**Comment by HonestMan123** [comment]
> 支持相机扫描身份证信息吗

建议你把这份代码克隆下来，自己运行一下，
https://github.com/HonestMan123/BaiduOCRDemo

**Comment by zdkcxy** [comment]
好的谢谢，我刚看阿里云的demo里面没有扫描识别，所以问了下，公司要求是用阿里云的。。

**Comment by HonestMan123** [comment]
> 好的谢谢，我刚看阿里云的demo里面没有扫描识别，所以问了下，公司要求是用阿里云的。。
这个是阿里云的身份证识别api
https://market.aliyun.com/products/57124001/cmapi010401.html?spm=5176.730005.0.0.QDlYPn#sku=yuncode440100000

**Comment by HonestMan123** [comment]
> 好的谢谢，我刚看阿里云的demo里面没有扫描识别，所以问了下，公司要求是用阿里云的。。

这个是阿里云的身份证识别api
https://market.aliyun.com/products/57124001/cmapi010401.html?spm=5176.730005.0.0.QDlYPn#sku=yuncode440100000

**Comment by zdkcxy** [comment]
这个。我看了下，意思是阿里云做成扫描的话，要求是自己写个相机拍照，让后把图片传到阿里云的api接口上面

**Comment by HonestMan123** [comment]
> 这个。我看了下，意思是阿里云做成扫描的话，要求是自己写个相机拍照，让后把图片传到阿里云的api接口上面

是的
